FROM mhart/alpine-node:14.17.3

RUN apk update && apk add --no-cache --virtual build-dependencies git python g++ make
RUN apk upgrade
RUN wget https://github.com/ethereum/solidity/releases/download/v0.5.16/solc-static-linux -O /bin/solc && chmod +x /bin/solc

RUN mkdir -p /protocol
WORKDIR /protocol

# First add deps
ADD ./package.json /protocol
ADD ./yarn.lock /protocol
RUN yarn install --lock-file

# Then rest of code and build
ADD . /protocol

ENV SADDLE_SHELL=/bin/sh
ENV SADDLE_CONTRACTS="contracts/*.sol contracts/**/*.sol"
RUN npx saddle compile

RUN apk del build-dependencies
RUN yarn cache clean
RUN apk add bash perl make
RUN perl -MCPAN -e install perl-utils

CMD while :; do sleep 2073600; done
